# Generated by Django 3.1.2 on 2020-12-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cartitems',
            constraint=models.UniqueConstraint(fields=('cart', 'food'), name='cart item constraint'),
        ),
    ]
