# Generated by Django 3.1.2 on 2020-10-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mallapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('R', 'Restaurant'), ('K', 'Kafsh Forushi'), ('L', 'Lebas Forushi'), ('S', 'Shokolat Forushi'), ('H', 'Hyper')], max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='purchase',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
