# Generated by Django 3.1.2 on 2021-01-08 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_a'),
    ]

    operations = [
        migrations.DeleteModel(
            name='A',
        ),
    ]
