# Generated by Django 3.1.2 on 2020-11-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20201114_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='descriptions',
            field=models.CharField(default='توضیحات را ویرایش کنید', max_length=250),
        ),
    ]
