# Generated by Django 3.1.2 on 2020-11-14 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementaddress',
            name='address_txt',
            field=models.TextField(default='tehran'),
        ),
        migrations.AlterField(
            model_name='elementaddress',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='restaurant.element'),
        ),
    ]
