# Generated by Django 3.1.2 on 2020-11-14 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='poster',
        ),
    ]
