# Generated by Django 3.1.2 on 2020-11-20 12:42

from django.db import migrations, models
import django.db.models.deletion
import restaurant.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_menucat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('rate', models.FloatField(default=5)),
                ('poster', models.ImageField(blank=True, null=True, upload_to=restaurant.models.get_upload_path)),
                ('cat_manu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.menucat')),
            ],
        ),
    ]
