# Generated by Django 3.1.2 on 2020-11-08 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('answer', models.IntegerField(default=1)),
                ('option1', models.CharField(max_length=40)),
                ('option2', models.CharField(max_length=40)),
                ('option3', models.CharField(blank=True, max_length=40)),
                ('option4', models.CharField(blank=True, max_length=40)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.category')),
            ],
        ),
    ]
