# Generated by Django 3.1.2 on 2020-11-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='priority_address',
            field=models.SmallIntegerField(default=1),
        ),
    ]
