version: "3.7"

services:
  django_web:
    build: .
    command: python manage.py migrate
    volumes:
      - static:/app/static
      - media:/app/media
    command: gunicorn mapsafood.wsgi:application --bind 0.0.0.0:8000
    ports: 
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ashkan
      - POSTGRES_PASSWORD=mapsa
      - POSTGRES_DB=mapsafood

  nginx:
    build: ./nginx
    volumes:
      - static:/app/static
      - media:/app/media
    ports:
      - 8080:80
    depends_on:
      - django_web

volumes:
  postgres_data:
  static:
  media:
